config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .settings import dev

urlpatterns = [
                  path('', include('newsfeed.urls')),
                  path('admin/', admin.site.urls),
                  path("ckeditor/", include('ckeditor_uploader.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if dev.DEBUG:
    import debug_toolbar
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

newsfeed/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from config.settings import base
from .views import SignUpUser, SignInUser, AddNews, HomeListView, NewsDetailView

urlpatterns = [
    path('', HomeListView.as_view(), name='index'),
    path('news/<slug>/', NewsDetailView.as_view(), name='news_detail'),
    path('signup/', SignUpUser.as_view(), name='signup'),
    path('signin/', SignInUser.as_view(), name='signin'),
    path('signout/', LogoutView.as_view(), {'next_page': base.LOGOUT_REDIRECT_URL}, name='signout', ),
    path('add_news/', AddNews.as_view(), name='add_news'),
]

newsfeed/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class News(models.Model):
    title = models.CharField('Заголовок', max_length=200)
    slug = models.SlugField(max_length=255)
    content = RichTextUploadingField('Тело новости')
    # image = models.ImageField('Изображение', blank=True)
    created_at = models.DateTimeField('Дата создания', auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'news'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('news', kwargs={"slug": self.slug})

newsfeed/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import News


class AddNewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ('title', 'content',)
        # fields = ('title', 'content', 'image',)

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'content': forms.Textarea(attrs={'cols': 60, 'rows': 10}),
        }


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "id": "inputUsername",
                "placeholder": "Имя пользователя",
            }
        ),
    )
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={
                "class": "form-control mt-2",
                "id": "inputPassword",
                "placeholder": "Почта",
            }
        ),
    )
    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control mt-2",
                "id": "inputPassword",
                "placeholder": "Пароль",
            }
        ),
    )
    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control mt-2",
                "id": "inputPassword",
                "placeholder": "Повторите пароль",
            }
        ),
    )


class SignInForm(AuthenticationForm):
    username = forms.CharField(
        label="Логин",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "id": "inputUsername",
                "placeholder": "Имя пользователя",
            }
        ),
    )
    password = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control mt-2",
                "id": "inputUsername",
                "placeholder": "Пароль",
            }
        ),
    )

newsfeed/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views import View
from django.views.generic import CreateView, ListView, DetailView

from .forms import SignUpForm, SignInForm
from .models import News


class HomeListView(ListView):
    template_name = 'newsfeed/home.html'
    model = News
    paginate_by = 10

    ordering = ['-created_at']

    def get_paginate_by(self, queryset):
        return self.request.GET.get('paginate_by', self.paginate_by)

    
class NewsDetailView(DetailView):
    model = News
    template_name = 'newsfeed/news_detail.html'


class AddNews(CreateView):
    template_name = 'newsfeed/add_news.html'
    model = News
    fields = ('title', 'content',)
    # fields = ('title', 'content', 'image',)
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        form.instance.author = self.request.user
        news = form.save(commit=False)
        news.slug = slugify(news.title)
        return super(AddNews, self).form_valid(form)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(News, self).save(*args, **kwargs)


class SignUpUser(CreateView):
    form_class = SignUpForm
    template_name = "newsfeed/signup.html"
    success_url = reverse_lazy("signin")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect("index")


class SignInUser(LoginView):
    form_class = SignInForm
    template_name = "newsfeed/signin.html"

    def get_success_url(self):
        return reverse_lazy("index")


def logout_user(request):
    logout(request)
    return redirect("signin")


# Create your views here.
def get_view(request):
    print(request.GET)
    print(request.GET.get('paginate_by'))
    return render(request, "newsfeed/get_form.html")


def post_view(request):
    print(request.POST)
    print(request.POST.get('paginate_by'))
    return render(request, "newsfeed/post_form.html")

templates/newsfeed/add_news.html
{% extends './base.html' %}
{% load static %}
{% block title %}Добавить новость{% endblock %}

{% block content %}
    <div class="text-center">

        <h1>Добавить новость</h1>
        <form action="" enctype='multipart/form-data' method="POST">{% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <input type="submit" value="Save"/>
        </form>
    </div>
{% endblock %}

templates/newsfeed/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">


{#    <style>#}
{#        body {#}
{#            margin-bottom: 60px;#}
{#        }#}
{##}
{#        html {#}
{#            position: relative;#}
{#            min-height: 100%;#}
{#        }#}
{##}
{#        footer {#}
{#            position: absolute;#}
{#            bottom: 0;#}
{#            width: 100%;#}
{#            height: 60px;#}
{#            line-height: 60px;#}
{#            background-color: #f5f5f5;#}
{#        }#}
{#    </style>#}

</head>
<body>
{% include './block/navbar.html' %}

{% block header %}{% endblock %}

{% block content %}{% endblock %}

{% block pagination %}{% endblock %}

{% include './block/footer.html' %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
{#    <script src="{% static 'js/script.js' %}"></script>#}
</body>
</html>

templates/newsfeed/block/footer.html
<footer class="footer">
  <div class="container">
    <p class="float-right">
      <a href="#">Наверх</a>
    </p>
    <span class="text-muted">Чолпонбек уулу Жоомарт</span>
  </div>
</footer>

templates/newsfeed/block/header.html
{% load static %}
<div class="container-fluid home-slider">
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active" style="background-color: #343a40!important">
                <div class="carousel-caption d-none d-md-block">
                    <h1>
                        {% if news.title %}
                            {{ news.title }}
                        {% else %}
                            {{ title }}
                        {% endif %}
                    </h1>
                </div>
            </div>
        </div>
    </div>
</div>

templates/newsfeed/block/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <a href="#" class="navbar-brand">
        <img src="https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg" width="30" height="30"
             alt="logo">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a href="{% url 'index' %}" class="nav-link">Главная</a>
            </li>
            <li class="nav-item ">
                <a href="#" class="nav-link">Контакты</a>
            </li>
        </ul>
        {% if user.is_authenticated %}
            <span class="navbar-text mr-2">{{ user }}</span>
            <a href="{% url 'add_news' %}" class="btn btn-primary mr-2">Добавить новость</a>
            <a href="{% url 'signout' %}" class="btn btn-outline-light">Выход</a>
        {% else %}
            <a href="{% url 'signin' %}" class="btn btn-outline-light mr-2">Вход</a>
            <a href="{% url 'signup' %}" class="btn btn-outline-light mr-2">Регистрация</a>
        {% endif %}
    </div>
</nav>

templates/newsfeed/home.html
{% extends './base.html' %}
{% load static %}

{% block title %}Главная страница{% endblock %}


{% block content %}
    <div class="container">
        <h1 class="my-3">Последние новости</h1>
        <h5 class="my-3"> Выберите количество новостей для отображения на странице</h5>
        <form action="." method="get">{% csrf_token %}
            <select name="paginate_by" type="number">
                <option>10</option>
                <option>20</option>
                <option>50</option>
            </select>
            <input type="submit" value="Сохранить"/>
        </form>

        <div class="row">
            {% for news in news_list %}
                <div class="col-md-4">
                    <div class="card mb- shadow-sm">
{#                        {% if news.image %}#}
{#                            <img src="media/{{ news.image }}" alt="" class="card-img-top"#}
{#                                 width="348" height="300">#}
{#                        {% endif %}#}
                        <div class="card-body">
                            <h4 class="card-title">{{ news.title|truncatechars:100 }}</h4>
                            {{ news.content|safe|truncatechars:200 }}
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'news_detail' slug=news.slug %}"
                                       class="btn btn-sm btn-outline-secondary">Подробнее</a>
                                </div>
                                <small class="text-muted">{{ news.created_at }}</small>
                                <small class="text-muted">{{ news.author }}</small>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block pagination %}
    <nav aria-label="Paginate me">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Предыдущая</a>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link disabled" href="#" tabindex="-1">Предыдущая</a>
                </li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
                {% if i == page_obj.number %}
                    <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Следующая</a>
                </li>
            {% endif %}
        </ul>
    </nav>
    <br>
{% endblock %}

templates/newsfeed/news_detail.html
{% extends './base.html' %}
{% load static %}
{% block title %}{{ news.title }}{% endblock %}

{% block header %}
    {% include './block/header.html' %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <nav aria-label="breadcrumb" class="mt-4">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'index' %}">Главная</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{{ news.title }}</li>
                    </ol>
                </nav>

{#                <img class="img-fluid rounded " src="/media/{{ news.image }}" alt="">#}

                <hr>
                <p class="lead">
                    {{ news.content|safe }}
                </p>
                <hr>
                <p class="lead text-right">Автор: {{ news.author }}</p>
                <hr>
                <p class="text-right">Опубликовано {{ news.created_at }}</p>
                <hr>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/newsfeed/signin.html
{% extends './base.html' %}
{% load static %}
{% block title %}Вход{% endblock %}

{% block content %}
    <div class="text-center">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}

        <div class="col-md-4 mb-3 mx-auto">
            <form class="form-signin" method="post" action="{% url 'signin' %}">
                {% csrf_token %}
                <h1 class="h3 mb-3 mt-3 font-weight-normal">Пожалуйста укажите логин и пароль</h1>
                <label for="inputUsername" class="sr-only">Имя пользователя</label>
                {{ form.username }}
                <label for="inputPassword" class="sr-only">Пароль</label>
                {{ form.password }}
                <button class="btn mt-2 btn-lg btn-primary btn-block" type="submit">Войти</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/newsfeed/signup.html
{% extends './base.html' %}
{% load static %}
{% block title %}Регистрация{% endblock %}


{% block content %}
    <div class="text-center">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <div class="col-md-4 mb-3 mx-auto">
            <form method="post">
                {% csrf_token %}
                <h1 class="h3 mb-3 mt-3 font-weight-normal">Для регистрации укажите имя пользователя и пароль</h1>
                <label for="inputUsername" class="sr-only">Имя пользователя</label>
                {{ form.username }}
                <label for="inputEmail" class="sr-only">Почта</label>
                {{ form.email }}
                <label for="inputPassword" class="sr-only">Пароль</label>
                {{ form.password1 }}
                <label for="ReInputPassword" class="sr-only">Повторите пароль</label>
                {{ form.password2 }}
                <button class="btn mt-2 btn-lg btn-primary btn-block" type="submit">Регистрация</button>
            </form>
        </div>
    </div>

{% endblock %}